name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 6.0.2
        run_install: |
          - recursive: true
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
